Add GitHub Actions workflow for deployment to AWS

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,97 +8,69 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read
+      contents: write
     outputs:
       self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
     env:
       CI: "true"
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           ref: ${{ github.event.pull_request.head.ref }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Install dependencies
         run: npm install
-      - name: Build project
-        run: npm run build
-      - name: Build with Projen
+      - name: build
         run: npx projen build
       - name: Find mutations
         id: self_mutation
-        run: "
-
-          \          git add .
-
-          \          if git diff --staged --quiet; then
-
-          \            echo \"self_mutation_happened=false\" >> $GITHUB_ENV
-
-          \          else
-
-          \            git diff --staged --patch > .repo.patch
-
-          \            echo \"self_mutation_happened=true\" >> $GITHUB_ENV
-
-          \          fi
-
-          \        "
+        run: |-
+          git add .
+          git diff --staged --patch --exit-code > repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
+        shell: bash
+        working-directory: ./
       - name: Upload patch
-        if: env.self_mutation_happened == true
-        uses: actions/upload-artifact@v4
+        if: steps.self_mutation.outputs.self_mutation_happened
+        uses: actions/upload-artifact@v7
         with:
-          name: .repo.patch
-          path: .repo.patch
+          name: repo.patch
+          path: repo.patch
           overwrite: true
       - name: Fail build on mutation
-        if: env.self_mutation_happened == true
-        run: "
-
-          \          echo \"::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch.\"
-
-          \          cat .repo.patch
-
-          \          exit 1
-
-          \        "
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat repo.patch
+          exit 1
   self-mutation:
     needs: build
     runs-on: ubuntu-latest
     permissions:
       contents: write
-    if: always() && needs.build.outputs.self_mutation_happened == true && !(github.event.pull_request.head.repo.full_name != github.repository)
+    if: always() && needs.build.outputs.self_mutation_happened && !(github.event.pull_request.head.repo.full_name != github.repository)
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
           ref: ${{ github.event.pull_request.head.ref }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Download patch
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v8
         with:
-          name: .repo.patch
+          name: repo.patch
           path: ${{ runner.temp }}
       - name: Apply patch
-        run: '[ -s ${{ runner.temp }}/.repo.patch ] && git apply ${{ runner.temp }}/.repo.patch || echo "Empty patch. Skipping."'
+        run: '[ -s ${{ runner.temp }}/repo.patch ] && git apply ${{ runner.temp }}/repo.patch || echo "Empty patch. Skipping."'
       - name: Set git identity
-        run: "
-
-          \          git config user.name \"github-actions\"
-
-          \          git config user.email \"github-actions@github.com\"
-
-          \        "
+        run: |-
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
       - name: Push changes
         env:
           PULL_REQUEST_REF: ${{ github.event.pull_request.head.ref }}
-        run: "
-
-          \          git add .
-
-          \          git commit -s -m \"chore: self mutation\"
-
-          \          git push origin HEAD:$PULL_REQUEST_REF
-
-          \        "
+        run: |-
+          git add .
+          git commit -s -m "chore: self mutation"
+          git push origin "HEAD:$PULL_REQUEST_REF"
